name: Gerar Instalador Windows

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Baixar os ficheiros do projeto
        uses: actions/checkout@v4

      - name: Instalar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Atualizado para a versão LTS estável (remove o aviso)

      - name: Instalar as dependências
        run: npm install

      - name: Gerar o instalador .exe
        run: npm run build-win

      - name: Salvar o instalador para download
        uses: actions/upload-artifact@v4
        with:
          name: Instalador-Gerador-PEI
          path: dist/*.exe
